
/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the UFT Developer Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/
package g1;

import com.hp.lft.sdk.*;

// This class is automatically generated by the UFT Developer Application Model code generator
public class MyAppModel extends AppModelBase {	
	public MyAppModel(TestObject contextTestObject) throws GeneralLeanFtException
	{
		setName("MyAppModel");
		rebuildDescriptions();
	}	
}
